import { useState, useRef, useEffect, useCallback } from 'react'
import { useDropzone } from 'react-dropzone'
import jsPDF from 'jspdf'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx'
import { saveAs } from 'file-saver'
import toast from 'react-hot-toast'
import { Upload, X, Loader2, Paperclip, Mic, ArrowUp, Sparkles, FileText, File, Layout, FileLineChart } from 'lucide-react'

import { supabase, isSupabaseConfigured } from '../../lib/supabase'
import { localDB, useAuth } from '../../context/AuthContext'

const API = import.meta.env.VITE_API_URL || (import.meta.env.PROD ? '' : 'http://localhost:5000')

// ─── exports ──────────────────────────────────────────────────────────────────
function dlPDF(doc) {
  const pdf = new jsPDF(), pw = pdf.internal.pageSize.getWidth(), mg = 15
  let y = 0
  const np = () => { pdf.addPage(); y = 20 }
  const cy = (n=12) => { if (y+n>275) np() }
  pdf.setFillColor(25,25,25); pdf.rect(0,0,pw,28,'F') // Claude dark style
  pdf.setFontSize(12); pdf.setTextColor(255,255,255); pdf.setFont('helvetica','bold')
  pdf.text('TNEB Official Document', pw/2, 11, {align:'center'})
  pdf.setFontSize(8); pdf.setFont('helvetica','normal')
  pdf.text('AI Generated', pw/2, 20, {align:'center'})
  y = 36
  pdf.setFontSize(15); pdf.setTextColor(20,20,20); pdf.setFont('helvetica','bold')
  pdf.splitTextToSize(doc.title, pw-mg*2).forEach(l=>{ pdf.text(l,mg,y); y+=7 })
  pdf.setFontSize(7.5); pdf.setTextColor(120); pdf.setFont('helvetica','normal')
  pdf.text(`Generated: ${new Date().toLocaleString('en-IN')}`, mg, y); y+=4
  pdf.setDrawColor(200,200,200); pdf.setLineWidth(0.5); pdf.line(mg,y,pw-mg,y); y+=8
  doc.sections.forEach(s => {
    cy(16)
    pdf.setFontSize(11); pdf.setTextColor(20,20,20); pdf.setFont('helvetica','bold')
    pdf.text(s.title, mg, y); y+=4
    pdf.setDrawColor(230,230,230); pdf.setLineWidth(0.3); pdf.line(mg,y,pw-mg,y); y+=5
    pdf.setFontSize(9.5); pdf.setTextColor(50); pdf.setFont('helvetica','normal')
    pdf.splitTextToSize(s.content||'', pw-mg*2).forEach(l=>{ cy(5); pdf.text(l,mg,y); y+=5 })
    y+=5
  })
  const pg = pdf.internal.getNumberOfPages()
  for (let p=1;p<=pg;p++) { pdf.setPage(p); pdf.setFontSize(7); pdf.setTextColor(160); pdf.text(`${p}/${pg}`,pw/2,290,{align:'center'}) }
  pdf.save(doc.title.replace(/\s+/g,'_').slice(0,60)+'.pdf')
  toast.success('PDF downloaded')
}

async function dlDOCX(doc) {
  const ch = [
    new Paragraph({ text:'TNEB OFFICIAL DOCUMENT', heading:HeadingLevel.HEADING_1, alignment:AlignmentType.CENTER }),
    new Paragraph({ children:[new TextRun({ text:doc.title, bold:true, size:26, color:'000000' })], alignment:AlignmentType.CENTER }),
    new Paragraph({ children:[new TextRun({ text:`Generated: ${new Date().toLocaleString('en-IN')}`, size:17, color:'888888' })], alignment:AlignmentType.CENTER }),
    new Paragraph({text:''}),
    ...doc.sections.flatMap(s=>[
      new Paragraph({ children:[new TextRun({text:s.title,bold:true,size:22,color:'000000'})], heading:HeadingLevel.HEADING_2, spacing:{before:280,after:100}, border:{bottom:{color:'cccccc',size:6,style:BorderStyle.SINGLE}} }),
      ...(s.content||'').split('\n').map(l=>new Paragraph({children:[new TextRun({text:l,size:19})],spacing:{after:70}}))
    ]),
    new Paragraph({ children:[new TextRun({text:`\nGenerated by TNEB AI`,size:15,color:'888888',italics:true})], alignment:AlignmentType.CENTER })
  ]
  const blob = await Packer.toBlob(new Document({ sections:[{properties:{},children:ch}], title:doc.title, creator:'TNEB' }))
  saveAs(blob, doc.title.replace(/\s+/g,'_').slice(0,60)+'.docx')
  toast.success('DOCX downloaded')
}

// ─── Typewriter hook ──────────────────────────────────────────────────────────
function useTypewriter(target, speed = 12) {
  const [display, setDisplay] = useState('')
  const [done, setDone] = useState(false)
  const ref = useRef({ timer: null, idx: 0, prev: '' })

  useEffect(() => {
    if (target === ref.current.prev) return
    clearInterval(ref.current.timer)
    ref.current.prev = target
    ref.current.idx  = 0
    setDone(false)

    ref.current.timer = setInterval(() => {
      ref.current.idx += speed
      const next = target.slice(0, ref.current.idx)
      setDisplay(next)
      if (ref.current.idx >= target.length) {
        setDisplay(target)
        setDone(true)
        clearInterval(ref.current.timer)
      }
    }, 16)
    return () => clearInterval(ref.current.timer)
  }, [target])

  return { display, done }
}

// ─── Message block ───────────────────────────────────────────────────────────
function Msg({ m, isLast }) {
  const isUser = m.role === 'user'
  const raw = m.content || ''

  const { display } = useTypewriter(
    (!isUser && isLast && !m.settled) ? raw : raw,
    (!isUser && isLast && !m.settled) ? 8 : 9999
  )

  const text = (!isUser && isLast && !m.settled) ? display : raw

  return (
    <div className={`flex gap-4 mb-8 ${isUser ? 'flex-row-reverse' : ''} animate-fade-in group`}>
      {/* Avatar */}
      <div className={`w-9 h-9 rounded-full flex items-center justify-center shrink-0 shadow-sm border transition-transform group-hover:scale-105
        ${isUser ? 'bg-slate-800 text-white border-slate-700' : 'bg-gradient-to-br from-indigo-500 to-purple-600 text-white border-indigo-400/50'}
      `}>
        {isUser ? 'U' : <Sparkles className="w-5 h-5 text-white/90" />}
      </div>

      {/* Content */}
      <div className={`flex-1 min-w-0 flex ${isUser ? 'justify-end' : 'justify-start'}`}>
        <div className={`max-w-[85%] rounded-2xl px-5 py-3.5 text-[15px] leading-relaxed shadow-sm
          ${isUser 
            ? 'bg-slate-100 text-slate-800 border border-slate-200/60 rounded-tr-sm' 
            : 'bg-white text-slate-700 border border-slate-100 rounded-tl-sm'}
        `}>
          {m.typing ? (
            <span className="flex gap-1.5 items-center py-1 h-6">
              {[0,1,2].map(i=>(
                <span key={i} className="w-2 h-2 rounded-full bg-indigo-400/60 animate-bounce"
                  style={{ animationDelay:`${i*0.15}s` }} />
              ))}
            </span>
        ) : (
          <span className="whitespace-pre-wrap">{text}</span>
        )}
        
          {/* Attached Files rendering */}
          {m.files?.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-2">
              {m.files.map((f,i)=>(
                <span key={i} className="flex items-center gap-2 text-xs font-medium bg-white/80 border border-slate-200 rounded-lg px-3 py-1.5 shadow-[0_1px_2px_rgba(0,0,0,0.02)] text-slate-600">
                  <FileText className="w-3.5 h-3.5 text-indigo-500" /> {f.name}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Document Preview Panel ───────────────────────────────────────────────────
function DocPanel({ doc, streaming }) {
  if (!doc) return (
    <div className="flex flex-col items-center justify-center h-full text-center p-10 bg-slate-50/50">
      <div className="w-16 h-16 rounded-2xl bg-white shadow-sm border border-slate-200 flex items-center justify-center mb-5">
        <Layout className="w-8 h-8 text-slate-300" />
      </div>
      <h3 className="font-semibold text-slate-700 text-lg mb-1">Canvas</h3>
      <p className="text-slate-500 text-sm max-w-sm leading-relaxed">
        Your generated documents will appear here. You can ask Claude to modify, reformat, or rewrite specific sections.
      </p>
    </div>
  )

  return (
    <div className="h-full overflow-y-auto bg-[#f8fafc] flex justify-center p-4 sm:p-8 custom-scrollbar">
      {/* A4 Paper Canvas */}
      <div className="bg-white w-full max-w-[800px] shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-200/60 p-10 sm:p-14 
                      transition-all duration-300 relative min-h-[1056px] rounded-sm">
        {/* TNEB header inside canvas */}
        <div className="flex items-center gap-4 border-b-2 border-slate-800 pb-6 mb-10">
          <div className="w-16 h-16 rounded-full overflow-hidden border border-slate-200 shrink-0 shadow-sm">
            <img src="https://upload.wikimedia.org/wikipedia/en/e/e9/Tamil_Nadu_Electricity_Board_%28emblem%29.jpg"
              alt="TNEB" className="w-full h-full object-cover"
              onError={e=>{e.target.src='/tneb-logo.png'}} />
          </div>
          <div className="flex-1 min-w-0">
            <h1 className="font-black text-2xl tracking-tight text-slate-900 uppercase font-serif">
              Tamil Nadu Electricity Board
            </h1>
            <p className="text-xs text-slate-500 mt-1 uppercase tracking-widest font-semibold">Official Communication</p>
          </div>
        </div>

        {/* Document content */}
        <div className="font-serif">
          <div className="text-center pb-8 mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-2 leading-tight">{doc.title}</h2>
            <p className="text-sm text-slate-500 font-sans tracking-wide">
              {new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}
            </p>
          </div>

          {doc.sections.map((s,i) => (
            <div key={i} className="mb-8 animate-fade-in">
              <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest
                             pb-2 mb-3 border-b border-slate-200">{s.title}</h3>
              <div className="text-[15px] text-slate-800 leading-relaxed whitespace-pre-wrap font-serif">
                {s.content}
                {streaming && i === doc.sections.length-1 && (
                  <span className="inline-block w-[3px] h-4 bg-slate-900 animate-pulse ml-1 align-middle" />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────
const STARTERS = [
  { icon: FileLineChart, label: 'Incident Report', desc: 'Draft an incident report for an outage' },
  { icon: FileText, label: 'Official Letter', desc: 'Write a formal letter to the IT department' },
  { icon: Layout, label: 'Meeting Minutes', desc: 'Summarize the technical review meeting' }
]

const LANGUAGES = [
  { code: 'en-IN', label: 'English' },
  { code: 'ta-IN', label: 'Tamil (தமிழ்)' },
  { code: 'hi-IN', label: 'Hindi (हिंदी)' },
  { code: 'te-IN', label: 'Telugu (తెలుగు)' },
  { code: 'ml-IN', label: 'Malayalam (മലയാളം)' },
  { code: 'kn-IN', label: 'Kannada (ಕನ್ನಡ)' },
  { code: 'bn-IN', label: 'Bengali (বাংলা)' },
  { code: 'mr-IN', label: 'Marathi (मराठी)' },
  { code: 'gu-IN', label: 'Gujarati (ગુજરાતી)' },
  { code: 'pa-IN', label: 'Punjabi (ਪੰਜਾਬੀ)' },
  { code: 'or-IN', label: 'Odia (ଓଡ଼ିଆ)' },
  { code: 'ur-IN', label: 'Urdu (اردو)' }
]

export default function DocGenerator() {
  const { user } = useAuth()
  const [language,  setLanguage]  = useState(LANGUAGES[0])
  const [msgs,   setMsgs]   = useState([{
    role:'assistant', settled:true,
    content:`Hello! I'm your AI Document Assistant. How can I help you today? \n\nYou can ask me to draft an official document from scratch, or attach a file (PDF/DOCX) for me to review or rewrite.`
  }])
  const [input,     setInput]     = useState('')
  const [interim,   setInterim]   = useState('')
  const [listening, setListening] = useState(false)
  const [voiceOk,   setVoiceOk]   = useState(false)
  const [busy,      setBusy]      = useState(false)
  const [doc,       setDoc]       = useState(null)
  const [streaming, setStreaming] = useState(false)
  const [files,     setFiles]     = useState([])   // pending attachments

  const chatRef  = useRef(null)
  const inputRef = useRef(null)
  const recog    = useRef(null)

  // Auto-resize textarea
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.style.height = 'auto'
      inputRef.current.style.height = Math.min(inputRef.current.scrollHeight, 200) + 'px'
    }
  }, [input, interim])

  // scroll chat to bottom
  useEffect(() => {
    if (chatRef.current) {
      const scroll = chatRef.current.scrollHeight
      chatRef.current.scrollTo({ top: scroll, behavior: 'smooth' })
    }
  }, [msgs])

  // speech init
  useEffect(() => {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SR) return
    setVoiceOk(true)
    const r = new SR(); r.continuous=true; r.interimResults=true; r.lang=language.code
    r.onresult = e => {
      let fin='',int=''
      for (let i=e.resultIndex;i<e.results.length;i++) {
        const t=e.results[i][0].transcript
        e.results[i].isFinal ? fin+=t : int+=t
      }
      if (fin) setInput(p=>(p+' '+fin.trim()).trim())
      setInterim(int)
    }
    r.onerror = e => { if(e.error!=='aborted') toast.error('Voice: '+e.error); setListening(false) }
    r.onend = () => { setListening(false); setInterim('') }
    recog.current = r
  }, [language.code])

  const toggleVoice = () => {
    if (!recog.current) return
    if (listening) { recog.current.stop(); setListening(false) }
    else { recog.current.start(); setListening(true); inputRef.current?.focus() }
  }

  // File Dropzone
  const onDrop = useCallback(async (acceptedFiles) => {
    if (!acceptedFiles.length) return;
    toast.loading('Extracting text from file...', { id:'file-upload' })
    
    const parsed = []
    for (const f of acceptedFiles) {
      const formData = new FormData()
      formData.append('document', f)
      try {
        const res = await fetch(`${API}/api/documents/upload`, {
          method: 'POST',
          body: formData
        })
        const data = await res.json()
        if (!res.ok) throw new Error(data.error)
        parsed.push({ name: f.name, text: data.text })
        toast.success(`📎 ${f.name} extracted successfully!`, { id:'file-upload' })
      } catch (err) {
        toast.error(`Failed to parse ${f.name}`, { id:'file-upload' })
      }
    }
    setFiles(p => [...p, ...parsed])
  }, [])
  const { getRootProps, getInputProps, isDragActive, open } = useDropzone({ 
    onDrop, 
    noClick: true,
    accept: {
      'application/pdf': ['.pdf'],
      'text/plain': ['.txt'],
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx']
    } 
  })

  // ── core send ──────────────────────────────────────────────────────────────
  const send = async (prompt) => {
    const rawText = (prompt || input + ' ' + interim).trim()
    if (!rawText && !files.length) return
    if (busy) return
    if (listening) { recog.current.stop(); setListening(false) }

    const capturedFiles    = [...files]
    const capturedInput    = rawText
    const capturedAttached = capturedFiles.map(f => `[FILE: ${f.name}]\n${f.text}`).join('\n\n---\n\n')

    setInput(''); setInterim(''); setFiles([]);
    if (inputRef.current) inputRef.current.style.height = 'auto'

    const logInteraction = (promptText, replyText) => {
      if (isSupabaseConfigured) {
        supabase.from('ai_chat_logs').insert({
          prompt: promptText,
          response: replyText,
          user_id: user?.id,
          created_at: new Date().toISOString()
        }).then(()=>{}).catch(()=>{})
      } else {
        localDB.saveAiChatLog({
          prompt: promptText,
          response: replyText,
          user_id: user?.id
        })
      }
    }

    let instruction = capturedInput
    if (!instruction && capturedFiles.length > 0) {
      instruction = `Analyze the attached file(s): ${capturedFiles.map(f=>f.name).join(', ')}`
    }
    if (instruction && capturedFiles.length > 0 && doc) {
      instruction = `${instruction}\n\n[Attached file content to use]:\n${capturedAttached.slice(0,2000)}`
    }

    setMsgs(p => [...p, {
      role: 'user', settled: true,
      content: capturedInput || `[Attached ${capturedFiles.map(f=>f.name).join(', ')}]`,
      files: capturedFiles
    }])

    setBusy(true); setStreaming(true)
    setMsgs(p => [...p, { role:'assistant', settled:false, typing:true, content:'' }])

    try {
      let data
      if (doc) {
        // AI Modification
        let modifiedSections = [...doc.sections]
        let aiUsed = false

        try {
           const aiRes = await fetch(`${API}/api/ai/modify`, {
             method: 'POST',
             headers: { 'Content-Type': 'application/json' },
             body: JSON.stringify({
               text: doc.sections.map(s => s.title + '\n' + s.content).join('\n\n'),
               instruction: instruction + (capturedAttached ? '\n\nAttachments:\n' + capturedAttached : ''),
               language: language.label
             })
           })
           const aiData = await aiRes.json()
           if (aiRes.ok && aiData.result && !aiData.result.includes('MOCK AI')) {
              modifiedSections = [{ title: 'Updated Content', content: aiData.result }]
              aiUsed = true
           }
        } catch (e) { console.error("OpenAI modify failed, falling back", e) }

        if (!aiUsed) {
           const res = await fetch(`${API}/api/docgen/modify`, {
             method: 'POST',
             headers: { 'Content-Type': 'application/json' },
             body: JSON.stringify({ currentDoc: doc, instruction: instruction, attachedText: capturedAttached, language: language.label })
           })
           const localData = await res.json()
           if (!res.ok) throw new Error(localData.error)
           
           if (localData.isChat) {
              setMsgs(p => p.filter(m => !m.typing).concat([{ role:'assistant', settled:false, content:localData.reply }]))
              logInteraction(capturedInput, localData.reply)
              setStreaming(true)
              setTimeout(() => {
                setMsgs(p => p.map((m,i) => i===p.length-1 ? {...m,settled:true} : m))
                setStreaming(false)
              }, 1200)
              return // End early, no doc update
           }
           modifiedSections = localData.sections
        }

        data = { ...doc, sections: modifiedSections }
        const reply = `I've updated the document based on your request. You can see the new version in the canvas on the right.`

        setMsgs(p => p.filter(m => !m.typing).concat([{ role:'assistant', settled:false, content:reply }]))
        logInteraction(capturedInput, reply)
        setDoc(data)
        setStreaming(true)
        setTimeout(() => {
          setMsgs(p => p.map((m,i) => i===p.length-1 ? {...m,settled:true} : m))
          setStreaming(false)
        }, 1200)

      } else {
        // GENERATE new document
        const ctx = capturedAttached ? `\n\nContext from attached files:\n${capturedAttached.slice(0, 3000)}` : ''
        const res = await fetch(`${API}/api/docgen/generate`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ conversation: instruction + ctx, language: language.label })
        })
        data = await res.json()
        if (!res.ok) throw new Error(data.error || 'Generation failed')

        if (data.isChat) {
            setMsgs(p => p.filter(m => !m.typing).concat([{ role:'assistant', settled:false, content:data.reply }]))
            logInteraction(capturedInput, data.reply)
            setStreaming(true)
            setTimeout(() => {
              setMsgs(p => p.map((m,i) => i===p.length-1 ? {...m,settled:true} : m))
              setStreaming(false)
            }, 1200)
            return // End early, no doc update
        }

        const reply = `I have drafted the **${data.title}** for you.\n\nIt's available in the canvas on the right. You can ask me to rephrase certain sections, make it more formal, or export it.`

        setMsgs(p => p.filter(m => !m.typing).concat([{ role:'assistant', settled:false, content:reply }]))
        logInteraction(capturedInput, reply)
        setDoc(data)
        setStreaming(true)
        setTimeout(() => {
          setMsgs(p => p.map((m,i) => i===p.length-1 ? {...m,settled:true} : m))
          setStreaming(false)
        }, 1500)
      }

    } catch (err) {
      setMsgs(p => p.filter(m => !m.typing).concat([{ role:'assistant', settled:true, content:`I encountered an error: ${err.message}` }]))
      setStreaming(false)
    } finally {
      setBusy(false)
    }
  }

  const handleKey = e => { if (e.key==='Enter'&&!e.shiftKey) { e.preventDefault(); send() } }
  const quickAction = (action) => { if (doc) send(action) }

  return (
    <div {...getRootProps()} className="flex h-[calc(100vh-120px)] bg-white rounded-3xl overflow-hidden relative shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-200/80">
      <input {...getInputProps()} />
      
      {/* Drag & Drop Overlay */}
      {isDragActive && (
        <div className="absolute inset-0 bg-white/95 z-50 flex flex-col items-center justify-center backdrop-blur-md transition-all">
          <div className="w-24 h-24 bg-indigo-50 text-indigo-500 rounded-full flex items-center justify-center mb-6 shadow-sm border border-indigo-100 animate-bounce">
            <Upload size={40} />
          </div>
          <h2 className="text-3xl font-bold text-slate-800 tracking-tight">Drop files to attach</h2>
          <p className="text-slate-500 mt-2 font-medium">Supports PDF, DOCX, and TXT</p>
        </div>
      )}

      {/* ═══ LEFT: Chat Area ═══ */}
      <div className="w-full lg:w-[45%] flex flex-col bg-[#fcfcfc] border-r border-slate-200/80 relative">
        
        {/* Header */}
        <div className="px-6 py-4 flex items-center justify-between z-10 bg-white/80 backdrop-blur-xl sticky top-0 border-b border-slate-100/50">
          <h2 className="font-semibold text-slate-800 flex items-center gap-2.5 tracking-tight">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-sm">
              <Sparkles className="w-3.5 h-3.5 text-white" />
            </div>
            AI Assistant
          </h2>
          <div className="flex items-center gap-3">
            <select
              value={language.code}
              onChange={(e) => setLanguage(LANGUAGES.find(l => l.code === e.target.value))}
              className="text-xs font-semibold px-3 py-1.5 rounded-full bg-indigo-50 text-indigo-700 border border-indigo-100 outline-none hover:bg-indigo-100 transition-colors cursor-pointer"
            >
              {LANGUAGES.map(l => (
                <option key={l.code} value={l.code}>{l.label}</option>
              ))}
            </select>
          {doc && (
            <button onClick={()=>{setDoc(null);setMsgs([{role:'assistant',settled:true,content:'Ready for a new task. What document would you like to create?'}])}}
              className="text-xs font-semibold px-4 py-1.5 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 transition-all shadow-sm hover:shadow">
              New Chat
            </button>
          )}
          </div>
        </div>

        {/* Chat History */}
        <div ref={chatRef} className="flex-1 overflow-y-auto px-4 sm:px-6 py-6 custom-scrollbar scroll-smooth">
          {msgs.map((m,i)=><Msg key={i} m={m} isLast={i===msgs.length-1} />)}

          {/* Starter Prompts */}
          {!doc && msgs.length < 3 && (
            <div className="mt-8 animate-fade-in">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {STARTERS.map((s,i)=>(
                  <button key={i} onClick={()=>send(s.desc)} disabled={busy}
                    className="p-5 text-left border border-slate-200/60 rounded-2xl bg-white hover:bg-indigo-50/50 transition-all duration-300 hover:border-indigo-200 hover:-translate-y-1 hover:shadow-md group">
                    <div className="w-10 h-10 rounded-full bg-slate-50 flex items-center justify-center group-hover:bg-indigo-100 transition-colors mb-3">
                      <s.icon className="w-5 h-5 text-slate-400 group-hover:text-indigo-600 transition-colors" />
                    </div>
                    <h3 className="font-semibold text-slate-800 text-sm mb-1 group-hover:text-indigo-900 transition-colors">{s.label}</h3>
                    <p className="text-xs text-slate-500 leading-relaxed">{s.desc}</p>
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Quick AI Modifiers */}
          {doc && !busy && (
             <div className="mt-2 flex flex-wrap gap-2 animate-fade-in justify-start">
               <button onClick={()=>quickAction('Make the document highly formal and suitable for senior government officials.')} className="px-4 py-2 bg-white text-slate-600 border border-slate-200/80 shadow-[0_1px_2px_rgba(0,0,0,0.02)] rounded-full text-xs font-semibold hover:bg-indigo-50 hover:text-indigo-600 hover:border-indigo-200 hover:-translate-y-0.5 transition-all">✨ Make Formal</button>
               <button onClick={()=>quickAction('Summarize this into 3 key bullet points.')} className="px-4 py-2 bg-white text-slate-600 border border-slate-200/80 shadow-[0_1px_2px_rgba(0,0,0,0.02)] rounded-full text-xs font-semibold hover:bg-indigo-50 hover:text-indigo-600 hover:border-indigo-200 hover:-translate-y-0.5 transition-all">📝 Summarize</button>
               <button onClick={()=>quickAction('Please correct any spelling and grammar mistakes.')} className="px-4 py-2 bg-white text-slate-600 border border-slate-200/80 shadow-[0_1px_2px_rgba(0,0,0,0.02)] rounded-full text-xs font-semibold hover:bg-indigo-50 hover:text-indigo-600 hover:border-indigo-200 hover:-translate-y-0.5 transition-all">✔️ Fix Grammar</button>
             </div>
          )}
          <div className="h-6" />
        </div>

        {/* Input Area (Claude style floating input) */}
        <div className="p-4 sm:p-6 bg-gradient-to-t from-[#fcfcfc] via-[#fcfcfc] to-transparent">
          
          {/* Attached Files Preview */}
          {files.length>0 && (
            <div className="flex flex-wrap gap-2 mb-3">
              {files.map((f,i)=>(
                <div key={i} className="flex items-center gap-2 text-xs font-semibold bg-indigo-50 border border-indigo-100 rounded-lg pl-3 pr-2 py-1.5 shadow-sm text-indigo-700">
                  <FileText className="w-4 h-4 text-indigo-500" />
                  <span className="truncate max-w-[150px]">{f.name}</span>
                  <button onClick={()=>setFiles(p=>p.filter((_,j)=>j!==i))} className="p-0.5 hover:bg-indigo-100 rounded-md text-indigo-400 hover:text-indigo-600 transition-colors">
                    <X className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          )}

          {/* Input Box */}
          <div className="relative bg-white border border-slate-200/80 shadow-[0_2px_12px_rgba(0,0,0,0.04)] rounded-2xl focus-within:shadow-[0_8px_30px_rgba(79,70,229,0.12)] focus-within:border-indigo-400 focus-within:ring-4 focus-within:ring-indigo-500/10 transition-all duration-300 flex flex-col">
            <textarea 
              ref={inputRef} 
              value={input+(interim?' '+interim:'')} 
              onChange={e=>setInput(e.target.value)} 
              onKeyDown={handleKey} 
              disabled={busy}
              placeholder={listening ? 'Listening...' : (doc ? 'Ask me to modify the document...' : 'Message Assistant...')}
              className="w-full bg-transparent resize-none outline-none text-[15px] text-slate-800 placeholder-slate-400 py-4 px-5 min-h-[56px] max-h-[200px]"
              rows={1}
            />
            
            {/* Input Toolbar */}
            <div className="flex items-center justify-between px-3 py-2 border-t border-slate-100/50">
              <div className="flex items-center gap-1">
                <button type="button" onClick={open} title="Attach file" className="p-2 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-xl transition-all">
                  <Paperclip className="w-4 h-4" />
                </button>
                {voiceOk && (
                  <button onClick={toggleVoice} disabled={busy} className={`p-2 rounded-xl transition-all ${listening ? 'text-red-500 bg-red-50 hover:bg-red-100 animate-pulse' : 'text-slate-400 hover:text-indigo-600 hover:bg-indigo-50'}`}>
                    <Mic className="w-4 h-4" />
                  </button>
                )}
              </div>
              
              <button 
                onClick={()=>send()} 
                disabled={busy||(!input.trim()&&!interim.trim()&&!files.length)} 
                className={`p-2.5 rounded-xl transition-all duration-300 ${
                  (input.trim()||interim.trim()||files.length) && !busy
                    ? 'bg-gradient-to-r from-indigo-500 to-indigo-600 text-white hover:from-indigo-600 hover:to-indigo-700 shadow-md shadow-indigo-500/20' 
                    : 'bg-slate-100 text-slate-400'
                }`}
              >
                {busy ? <Loader2 className="w-4 h-4 animate-spin"/> : <ArrowUp className="w-4 h-4 stroke-[2.5]" />}
              </button>
            </div>
          </div>
          <div className="text-center mt-3">
            <span className="text-[11px] font-medium text-slate-400">AI can make mistakes. Please verify important information.</span>
          </div>
        </div>
      </div>

      {/* ═══ RIGHT: Document Canvas ═══ */}
      <div className="hidden lg:flex flex-1 flex-col bg-slate-100 relative">
        {doc && (
          <div className="absolute top-6 right-8 z-10 flex items-center gap-2.5">
            {[
              { label:'PDF',  fn:()=>dlPDF(doc)  },
              { label:'DOCX', fn:()=>dlDOCX(doc) },
            ].map(b=>(
              <button key={b.label} onClick={b.fn} className="px-5 py-2.5 bg-white/90 backdrop-blur-sm text-slate-700 border border-slate-200/80 shadow-sm rounded-xl text-xs font-bold hover:bg-indigo-50 hover:text-indigo-600 hover:border-indigo-200 hover:-translate-y-0.5 hover:shadow transition-all duration-300 flex items-center gap-2">
                <span className="text-indigo-400 font-black">↓</span> {b.label}
              </button>
            ))}
          </div>
        )}
        <DocPanel doc={doc} streaming={streaming} />
      </div>
    </div>
  )
}
